server:
  port: 8081
  servlet:
    context-path: /event-service

spring:
  application:
    name: EVENT-SERVICE 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems?useSSL=false&serverTimezone=UTC
    username: root
    password: Aspire@123

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/